# -*- coding: utf-8 -*-
"""Sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YG4dbIbfpDmjhsFIQANvrlykpBeBiNvN
"""

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from gensim.models import KeyedVectors
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Conv1D, MaxPooling1D, Flatten, Dropout


import keras





# data = pd.read_csv(r"Tweets.csv")
# print(data)
# print(data)
# data.info(memory_usage='deep')
# print(data.columns)

# Read the data

air_tweet = pd.read_csv(r"Tweets.csv", usecols=["airline", "text"])
# print(air_tweet)

# air_tweet.info(memory_usage='deep')



file_path = '/content/Tweets.csv'
air_tweet = pd.read_csv(file_path)

air_tweet = air_tweet[['text', 'airline_sentiment']]


# DATA CLEANING
def remove_handles(text):
    return re.sub(r'@\w+', '', text).strip()


air_tweet['cleaned_text'] = air_tweet['text'].apply(remove_handles)

air_tweet['cleaned_text'] = air_tweet['cleaned_text'].str.lower()

air_tweet['cleaned_text'] = air_tweet['cleaned_text'].str.replace(r'[^\w\s]', '', regex=True)

# Stop words ,  Tokenization , Stemming


stop_words = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd",
              'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers',
              'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what',
              'which',
              'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be',
              'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and',
              'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about',
              'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from',
              'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here',
              'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other',
              'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't',
              'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y',
              'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't",
              'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't",
              'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won',
              "won't", 'wouldn', "wouldn't"]



def remove_stopwords(text):
    return ' '.join([word for word in text.split() if word not in stop_words])


air_tweet['cleaned_text'] = air_tweet['cleaned_text'].apply(remove_stopwords)
air_tweet['tokenized_text'] = air_tweet['cleaned_text'].apply(word_tokenize)



# Stemming
stemmer = PorterStemmer()


def stem_words(text):
    return [stemmer.stem(word) for word in text]


air_tweet['stemmed_text'] = air_tweet['tokenized_text'].apply(stem_words)
# print(air_tweet)


tokenizer = Tokenizer()
tokenizer.fit_on_texts(air_tweet['cleaned_text'])
word_index = tokenizer.word_index


# Convert tokens back to string after stemming

def join_words(word_list):
    return ' '.join(word_list)

# Create a new list to store the joined strings
joined_texts = []

# Loop through each element in the 'stemmed_text' column
for text in air_tweet['stemmed_text']:
    joined_text = join_words(text)
    joined_texts.append(joined_text)

# Assign the new list back to the 'stemmed_text' column
air_tweet['stemmed_text'] = joined_texts






# Vectorization using TF-IDF
vectorizer = TfidfVectorizer(max_features=1000)
X = vectorizer.fit_transform(air_tweet['stemmed_text']).toarray()
y = air_tweet['airline_sentiment']
vectorizer = TfidfVectorizer(max_features=1000)

# Fit the vectorizer to the 'stemmed_text' column and transform the text data into a numerical array
X = vectorizer.fit_transform(air_tweet['stemmed_text'])

# Convert the result to an array
X = X.toarray()

# Extract the target variable
y = air_tweet['airline_sentiment']
# print(y)

########################


# Load pre-trained GloVe vectors
glove_file = './glove.6B.100d.txt'  # Change this to your GloVe file path
embeddings_index = {}
with open(glove_file, 'r', encoding='utf8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embeddings_index[word] = coefs

# Create embedding matrix
def get_embedding_vector(word):
    return embeddings_index.get(word, np.zeros(100))

def average_word_embeddings(tokens):
    if not tokens:
        return np.zeros(100)
    vectors = [get_embedding_vector(token) for token in tokens]
    return np.mean(vectors, axis=0)

X_embeddings = np.array([average_word_embeddings(tokens) for tokens in air_tweet['tokenized_text']])

print(X_embeddings)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_embeddings, air_tweet['airline_sentiment'], test_size=0.2, random_state=42)

# Encode the labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(air_tweet['airline_sentiment'])

X_train, X_test, y_train, y_test = train_test_split(X_embeddings, y_encoded, test_size=0.2, random_state=42)


# # Train a Decision Tree model
# model = DecisionTreeClassifier(random_state=42)
# model.fit(X_train, y_train)
#
# # Predict and evaluate
# y_pred = model.predict(X_test)
# print(classification_report(y_test, y_pred))
# print("Accuracy:", accuracy_score(y_test, y_pred))

# # Train an SVM model
# svm_model = SVC(kernel='linear', random_state=42)
# svm_model.fit(X_train, y_train)
#
# # Predict and evaluate
# y_pred_svm = svm_model.predict(X_test)
# print("SVM Classification Report:")
# print(classification_report(y_test, y_pred_svm, target_names=label_encoder.classes_))
# print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

# K-Nearest Neighbours

# knn_model = KNeighborsClassifier(n_neighbors=5)  # You can adjust the number of neighbors
# knn_model.fit(X_train, y_train)
#
# # Predict and evaluate
# y_pred_knn = knn_model.predict(X_test)
# print("K-Nearest Neighbors Classification Report:")
# print(classification_report(y_test, y_pred_knn))
# print("K-Nearest Neighbors Accuracy:", accuracy_score(y_test, y_pred_knn))

#
# # Train a Random Forest model
# rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
# rf_model.fit(X_train, y_train)
#
# # Predict and evaluate
# y_pred_rf = rf_model.predict(X_test)
# print("Random Forest Classification Report:")
# print(classification_report(y_test, y_pred_rf))
# print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

# Train a model (e.g., Logistic Regression)
# from sklearn.linear_model import LogisticRegression
#
# model = LogisticRegression(max_iter=1000)
# model.fit(X_train, y_train)

# # Predict and evaluate
# y_pred = model.predict(X_test)
# print(classification_report(y_test, y_pred))
# print("Accuracy:", accuracy_score(y_test, y_pred))


# Train an XGBoost model

# Encode the labels
# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(air_tweet['airline_sentiment'])
#
#
# xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
# xgb_model.fit(X_train, y_train)
#
# # Predict and evaluate
# y_pred_xgb = xgb_model.predict(X_test)
# print("XGBoost Classification Report:")
# print(classification_report(y_test, y_pred_xgb))
# print("XGBoost Accuracy:", accuracy_score(y_test, y_pred_xgb))

# Train an AdaBoost model
# ada_model = AdaBoostClassifier(estimator=DecisionTreeClassifier(), n_estimators=50, random_state=42)
# ada_model.fit(X_train, y_train)

# # Predict and evaluate
# y_pred_ada = ada_model.predict(X_test)
# print("AdaBoost Classification Report:")
# print(classification_report(y_test, y_pred_ada, target_names=label_encoder.classes_))
# print("AdaBoost Accuracy:", accuracy_score(y_test, y_pred_ada))

# # Train a Bagging model
# bagging_model = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50, random_state=42)
# bagging_model.fit(X_train, y_train)

# # Predict and evaluate
# y_pred_bagging = bagging_model.predict(X_test)
# # print("Bagging Classification Report:")
# # print(classification_report(y_test, y_pred_bagging, target_names=label_encoder.classes_))
# # print("Bagging Accuracy:", accuracy_score(y_test, y_pred_bagging))

##################################


# Split the data
X_train_embeddings, X_test_embeddings, y_train_encoded, y_test_encoded = train_test_split(X_embeddings, y_encoded, test_size=0.2, random_state=42)

# Build and train LSTM model
embedding_dim = 100
# Create embedding matrix
embedding_matrix = np.zeros((len(word_index) + 1, embedding_dim))
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

max_length = 100


def build_lstm_model():
    model = Sequential()
    model.add(Embedding(input_dim=len(word_index) + 1,
                        output_dim=embedding_dim,
                        weights=[embedding_matrix],
                        input_length=max_length,
                        trainable=False))
    model.add(LSTM(units=128, dropout=0.2, recurrent_dropout=0.2))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model


lstm_model = build_lstm_model()
lstm_model.summary()
lstm_model.fit(X_train_embeddings, y_train_encoded, epochs=5, batch_size=32, validation_split=0.2)


# Evaluate LSTM model
lstm_predictions = lstm_model.predict(X_test_embeddings)
lstm_predicted_classes = np.argmax(lstm_predictions, axis=1)
y_test_classes = np.argmax(y_test_encoded, axis=1)
print("LSTM Classification Report:")
print(classification_report(y_test_classes, lstm_predicted_classes, target_names=label_encoder.classes_))
print("LSTM Accuracy:", accuracy_score(y_test_classes, lstm_predicted_classes))











# Ensure correct one-hot encoding of labels
# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(air_tweet['airline_sentiment'])
# y_encoded = tf.keras.utils.to_categorical(y_encoded, num_classes=3)

# # Split the data
# X_train_embeddings, X_test_embeddings, y_train_encoded, y_test_encoded = train_test_split(X_embeddings, y_encoded, test_size=0.2, random_state=42)
#
# # Build and train LSTM model
# def build_lstm_model():
#     model = Sequential()
#     model.add(Embedding(input_dim=len(word_index) + 1,
#                         output_dim=embedding_dim,
#                         weights=[embedding_matrix],
#                         input_length=max_length,
#                         trainable=False))
#     model.add(LSTM(units=128, dropout=0.2, recurrent_dropout=0.2))
#     model.add(Dense(3, activation='softmax'))
#     model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#     return model

# lstm_model = build_lstm_model()
# lstm_model.summary()
# lstm_model.fit(X_train_embeddings, y_train_encoded, epochs=5, batch_size=32, validation_split=0.2)

# # Evaluate LSTM model
# lstm_predictions = lstm_model.predict(X_test_embeddings)
# lstm_predicted_classes = np.argmax(lstm_predictions, axis=1)
# y_test_classes = np.argmax(y_test_encoded, axis=1)
# print("LSTM Classification Report:")
# print(classification_report(y_test_classes, lstm_predicted_classes, target_names=label_encoder.classes_))
# print("LSTM Accuracy:", accuracy_score(y_test_classes, lstm_predicted_classes))

embedding_matrix[i] = embedding_vector

!pip install nltk
import nltk
nltk.download('punkt')

import pandas as pd
import re
# ... (rest of your code)

# ... (your existing code)

air_tweet['cleaned_text'] = air_tweet['cleaned_text'].apply(remove_stopwords)
air_tweet['tokenized_text'] = air_tweet['cleaned_text'].apply(word_tokenize) # This should now work

# ... (rest of your code)